-- Target Database : DERBY

-- Tables
CREATE TABLE SHOPLIST.article (
	ID integer NOT NULL,
	NAME varchar(128) NOT NULL,
	DESCR varchar(500),
	SHELF varchar(10) NOT NULL,
	EAN13 varchar(13)
);
ALTER TABLE SHOPLIST.article ADD CONSTRAINT ARTICLE_SHOP_ARTICLE_PK PRIMARY KEY (ID);
CREATE INDEX ARTICLE_SHOP_ARTICLE_R_SHELF ON SHOPLIST.article (SHELF) ;
CREATE TABLE SHOPLIST.list (
	ID integer NOT NULL,
	NAME varchar(100) NOT NULL,
	"USER" varchar(10) NOT NULL,
	CREATE_DATE date
);
ALTER TABLE SHOPLIST.list ADD CONSTRAINT LIST_SHOP_LIST_PK PRIMARY KEY (ID);
CREATE INDEX LIST_SHOP_LIST_USER_FK ON SHOPLIST.list ("USER") ;
CREATE TABLE SHOPLIST.SHOP_LIST_L_ARTICLE (
	LIST_ID integer NOT NULL,
	ARTICLE_ID integer NOT NULL,
	QUANTITY integer NOT NULL,
	STATUS varchar(5) DEFAULT 'BUY' NOT NULL
);
ALTER TABLE SHOPLIST.SHOP_LIST_L_ARTICLE ADD CONSTRAINT SHOP_LIST_L_ARTICLE_SHOP_LIST_L_ARTICLE_PK PRIMARY KEY (LIST_ID,ARTICLE_ID);
CREATE INDEX SHOP_LIST_L_ARTICLE_SHOP_LIST_L_ARTICLE_LIST_FK ON SHOPLIST.SHOP_LIST_L_ARTICLE (LIST_ID) ;
CREATE INDEX SHOP_LIST_L_ARTICLE_SHOP_LIST_L_ARTICLE_ARTICLE_FK ON SHOPLIST.SHOP_LIST_L_ARTICLE (ARTICLE_ID) ;
CREATE TABLE SHOPLIST.shelf (
	CODE varchar(10) NOT NULL,
	NAME varchar(100) NOT NULL,
	"POSITION" integer NOT NULL
);
ALTER TABLE SHOPLIST.shelf ADD CONSTRAINT SHELF_SHOP_SHELF_PK PRIMARY KEY (CODE);
CREATE TABLE SHOPLIST.user (
	LOGIN varchar(10) NOT NULL,
	NAME varchar(100) NOT NULL,
	PROFILE varchar(10) DEFAULT 'USER' NOT NULL
);
ALTER TABLE SHOPLIST.user ADD CONSTRAINT USER_SHOP_USER_PK PRIMARY KEY (LOGIN);

-- Foreign key constraints 
ALTER TABLE SHOPLIST.article ADD CONSTRAINT SHOP_ARTICLE_L_SHELF FOREIGN KEY (SHELF) REFERENCES SHOPLIST.shelf (CODE) ON DELETE NO ACTION;
ALTER TABLE SHOPLIST.list ADD CONSTRAINT SHOP_ARTICLE_L_USER FOREIGN KEY ("USER") REFERENCES SHOPLIST.user (LOGIN) ON DELETE NO ACTION;
ALTER TABLE SHOPLIST.SHOP_LIST_L_ARTICLE ADD CONSTRAINT SHOP_LIST_L_ARTICLE_L_LIST FOREIGN KEY (LIST_ID) REFERENCES SHOPLIST.list (ID) ON DELETE CASCADE;
ALTER TABLE SHOPLIST.SHOP_LIST_L_ARTICLE ADD CONSTRAINT SHOP_LIST_L_ARTICLE_L_ARTICLE FOREIGN KEY (ARTICLE_ID) REFERENCES SHOPLIST.article (ID) ON DELETE NO ACTION;

