-- Target Database : MYSQL

-- Drop constraints

ALTER TABLE ARTICLE DROP FOREIGN KEY SHOP_ARTICLE_L_SHELF;
ALTER TABLE LIST DROP FOREIGN KEY SHOP_ARTICLE_L_USER;
ALTER TABLE SHOP_LIST_L_ARTICLE DROP FOREIGN KEY SHOP_LIST_L_ARTICLE_L_LIST;
ALTER TABLE SHOP_LIST_L_ARTICLE DROP FOREIGN KEY SHOP_LIST_L_ARTICLE_L_ARTICLE;
-- Drop tables

DROP TABLE ARTICLE;
DROP TABLE LIST;
DROP TABLE SHOP_LIST_L_ARTICLE;
DROP TABLE SHELF;
DROP TABLE USER;

