-- Target Database : MYSQL

-- Tables
CREATE TABLE article (
	ID integer NOT NULL COMMENT 'ID',
	NAME varchar(128) NOT NULL COMMENT 'Nom',
	DESCR TEXT NULL COMMENT 'Description',
	SHELF varchar(10) NOT NULL COMMENT 'Rayon',
	EAN13 varchar(13) NULL COMMENT 'Ean13'
) ENGINE = InnoDB;
ALTER TABLE article COMMENT='Article';
ALTER TABLE article ADD CONSTRAINT ARTICLE_SHOP_ARTICLE_PK PRIMARY KEY (ID);
CREATE INDEX ARTICLE_SHOP_ARTICLE_R_SHELF ON article (SHELF) ;
CREATE TABLE list (
	ID integer NOT NULL COMMENT 'ID',
	NAME varchar(100) NOT NULL COMMENT 'Titre',
	`USER` varchar(10) NOT NULL COMMENT 'Créateur',
	CREATE_DATE date NULL COMMENT 'Date de création'
) ENGINE = InnoDB;
ALTER TABLE list COMMENT='Liste de courses';
ALTER TABLE list ADD CONSTRAINT LIST_SHOP_LIST_PK PRIMARY KEY (ID);
CREATE INDEX LIST_SHOP_LIST_USER_FK ON list (`USER`) ;
CREATE TABLE SHOP_LIST_L_ARTICLE (
	LIST_ID integer NOT NULL COMMENT 'Liste',
	ARTICLE_ID integer NOT NULL COMMENT 'Article',
	QUANTITY integer NOT NULL COMMENT 'Quantité',
	STATUS varchar(5) DEFAULT 'BUY' NOT NULL COMMENT 'Statut'
) ENGINE = InnoDB;
ALTER TABLE SHOP_LIST_L_ARTICLE COMMENT='Ligne d''article';
ALTER TABLE SHOP_LIST_L_ARTICLE ADD CONSTRAINT SHOP_LIST_L_ARTICLE_SHOP_LIST_L_ARTICLE_PK PRIMARY KEY (LIST_ID,ARTICLE_ID);
CREATE INDEX SHOP_LIST_L_ARTICLE_SHOP_LIST_L_ARTICLE_LIST_FK ON SHOP_LIST_L_ARTICLE (LIST_ID) ;
CREATE INDEX SHOP_LIST_L_ARTICLE_SHOP_LIST_L_ARTICLE_ARTICLE_FK ON SHOP_LIST_L_ARTICLE (ARTICLE_ID) ;
CREATE TABLE shelf (
	CODE varchar(10) NOT NULL COMMENT 'Code',
	NAME varchar(100) NOT NULL COMMENT 'Nom',
	`POSITION` integer NOT NULL COMMENT 'Position'
) ENGINE = InnoDB;
ALTER TABLE shelf COMMENT='Rayon';
ALTER TABLE shelf ADD CONSTRAINT SHELF_SHOP_SHELF_PK PRIMARY KEY (CODE);
CREATE TABLE user (
	LOGIN varchar(10) NOT NULL COMMENT 'Login',
	NAME varchar(100) NOT NULL COMMENT 'Nom',
	`PASSWORD` varchar(100) NULL COMMENT 'Mot de passe',
	PROFILE varchar(10) DEFAULT 'USER' NOT NULL COMMENT 'Profil'
) ENGINE = InnoDB;
ALTER TABLE user COMMENT='Utilisateur';
ALTER TABLE user ADD CONSTRAINT USER_SHOP_USER_PK PRIMARY KEY (LOGIN);

-- Foreign key constraints 
ALTER TABLE article ADD CONSTRAINT SHOP_ARTICLE_L_SHELF FOREIGN KEY (SHELF) REFERENCES shelf (CODE) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE list ADD CONSTRAINT SHOP_ARTICLE_L_USER FOREIGN KEY (`USER`) REFERENCES user (LOGIN) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE SHOP_LIST_L_ARTICLE ADD CONSTRAINT SHOP_LIST_L_ARTICLE_L_LIST FOREIGN KEY (LIST_ID) REFERENCES list (ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE SHOP_LIST_L_ARTICLE ADD CONSTRAINT SHOP_LIST_L_ARTICLE_L_ARTICLE FOREIGN KEY (ARTICLE_ID) REFERENCES article (ID) ON DELETE RESTRICT ON UPDATE CASCADE;

