-- Target Database : MYSQL

-- Drop constraints

ALTER TABLE article DROP FOREIGN KEY SHOP_ARTICLE_L_SHELF;
ALTER TABLE list DROP FOREIGN KEY SHOP_ARTICLE_L_USER;
ALTER TABLE SHOP_LIST_L_ARTICLE DROP FOREIGN KEY SHOP_LIST_L_ARTICLE_L_LIST;
ALTER TABLE SHOP_LIST_L_ARTICLE DROP FOREIGN KEY SHOP_LIST_L_ARTICLE_L_ARTICLE;
-- Drop tables

DROP TABLE article;
DROP TABLE list;
DROP TABLE SHOP_LIST_L_ARTICLE;
DROP TABLE shelf;
DROP TABLE user;

